Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/26/2022
Var
r, area : real


Inicio
      escreval("Digite o valor do raio do circulo")
      leia(r)
      
      area <- pi * exp(r, 2)
      
      escreval("A area do circulo é de", area:8:3)


Fimalgoritmo