Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/21/2022
Var
idade : inteiro
salario : real
nome : caractere

Inicio
      idade <- 32
      salario <- 4560.9
      nome <- "Rafael"
      
      escreva("O funcionário ", nome, " ganha ", salario:8:2, " e tem ", idade, " anos.")


Fimalgoritmo