Algoritmo "numeorsImpares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/7/2022
Var
n, x, i : inteiro


Inicio
      escreval("Digite o valor de x:")
      leia(x)

      para i de 1 ate x faca
        se i % 2 <> 0 entao
         escreval(i)
        fimse

      fimpara
Fimalgoritmo