Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/25/2022
Var
x : real
y : real


Inicio
escreva("Digite um valor:")
leia(X)
x <- raizq(x)
escreval("Raiz Quadrada:", x)
escreval("Digite um valor e outro para elevar o numero:")
leia(x)
leia(y)
x <- exp(x, y)
escreval("Valor exponencial:", x)

Fimalgoritmo