Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 7/26/2022
Var
x, y, soma : real


Inicio
      escreval("Digite o valor de x:")
      leia(x)
      escreval("Digite o valor de y:")
      leia(Y)
      
      soma <- x + y
      
      escreval("A soma de x e y é:", soma)


Fimalgoritmo