Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/1/2022
Var
x, n, i : inteiro

Inicio

      escreval("Deseja a tabuada de qual valor?")
      leia(n)
        
      para i de 1 ate 10 faca
        x <- n * i
        escreval(n, " x", i, " =", x)
      fimpara


Fimalgoritmo